/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.MenuPrincipal;
import java.sql.ResultSet;

import java.sql.Statement;
import java.text.DateFormat;
import java.util.Calendar;
import Negocio.Entidades.Reloj;
import DatosPersistentes.ConectaBD;
import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Negocio.Entidades.Producto;
//import Negocio.Entidades.Ventas;
import java.util.Random;


/**
 *
 * @author Mario
 */
public class FrmVentas extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentas
     */
    
  
    public ArrayList ArregloProductos = new ArrayList();
    private double sumaTotal = 0.0;
    
    public FrmVentas() {
        initComponents();
        
       inicializaTabla(Tabla);
        
        
        Reloj hilo = new Reloj(lbRelojDato);
        hilo.start();
        
        Calendar unCalendario = Calendar.getInstance();
        DateFormat unFormatoFecha = DateFormat.getDateInstance(DateFormat.FULL);
        lbFechaDato.setText("" + unFormatoFecha.format(unCalendario.getTime()));
        
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        String capturaProductos = "";
        String capturaClientes = "";
        String sql = "select * from inventario";
        String sql2= "select * from clientes";
        this.comboProductos.removeAllItems();
        this.comboClientes.removeAllItems();
        
        //Agrega los nombres de los productos al ComboBox        
        try {
            Statement instruccion = cnx.createStatement();
            ResultSet conjuntoResultados = instruccion.executeQuery(sql);
            
            while(conjuntoResultados.next()){
                capturaProductos = conjuntoResultados.getString("Nombre");
                this.comboProductos.addItem(capturaProductos);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        //Agrega los nombres de los clientes al ComboBox
        try {
            Statement instruccion = cnx.createStatement();
            ResultSet conjuntoResultados = instruccion.executeQuery(sql2);
            
            while(conjuntoResultados.next()){
                capturaClientes = conjuntoResultados.getString("Nombre");
                this.comboClientes.addItem(capturaClientes);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbTituloVentas = new javax.swing.JLabel();
        lbNombreProducto = new javax.swing.JLabel();
        comboProductos = new javax.swing.JComboBox<String>();
        btAgregarProducto = new javax.swing.JButton();
        lbRelojDato = new javax.swing.JLabel();
        lbFechaDato = new javax.swing.JLabel();
        lbTotalDato = new javax.swing.JLabel();
        btEliminarProducto = new javax.swing.JButton();
        btRegresarMenu = new javax.swing.JButton();
        lbTotal = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btVerTotal = new javax.swing.JButton();
        btFinalizar = new javax.swing.JButton();
        lbNombreCliente = new javax.swing.JLabel();
        comboClientes = new javax.swing.JComboBox();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloVentas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTituloVentas.setForeground(new java.awt.Color(255, 0, 0));
        lbTituloVentas.setText("Ventas");

        lbNombreProducto.setText("Nombre del Producto:");

        comboProductos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProductosActionPerformed(evt);
            }
        });

        btAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/add.PNG"))); // NOI18N
        btAgregarProducto.setText("Agregar Producto");
        btAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarProductoActionPerformed(evt);
            }
        });

        lbRelojDato.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbRelojDato.setText("Hora: ");

        lbFechaDato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFechaDato.setText("Fecha");

        lbTotalDato.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        lbTotalDato.setForeground(new java.awt.Color(0, 0, 255));

        btEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/eliminar-icono-4399-128.png"))); // NOI18N
        btEliminarProducto.setText("Eliminar");
        btEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarProductoActionPerformed(evt);
            }
        });

        btRegresarMenu.setText("Regresar al Menu");
        btRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarMenuActionPerformed(evt);
            }
        });

        lbTotal.setText("TOTAL:");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        scrollPane1.add(jScrollPane2);

        btVerTotal.setText("Ver Total de Compra");
        btVerTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerTotalActionPerformed(evt);
            }
        });

        btFinalizar.setText("Finalizar Venta");
        btFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarActionPerformed(evt);
            }
        });

        lbNombreCliente.setText("Nombre del Cliente:");

        comboClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFechaDato, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNombreCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTituloVentas)
                                    .addComponent(comboProductos, 0, 197, Short.MAX_VALUE)
                                    .addComponent(comboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbRelojDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(296, 296, 296)
                                    .addComponent(lbTotal)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbTotalDato, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btEliminarProducto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btVerTotal)
                                    .addGap(36, 36, 36)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btRegresarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                                .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRelojDato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFechaDato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbTituloVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarProducto)
                    .addComponent(comboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreCliente)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btEliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btVerTotal)
                        .addGap(18, 18, 18)
                        .addComponent(lbTotalDato, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRegresarMenu)
                    .addComponent(btFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProductosActionPerformed
         
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        
        try {
            Statement instruccion2 = cnx.createStatement();
            ResultSet rs1 = instruccion2.executeQuery("select * from inventario where Nombre = '"
                    + this.comboProductos.getSelectedItem()+ "'");
            rs1.next();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_comboProductosActionPerformed

    private void btRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarMenuActionPerformed
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btRegresarMenuActionPerformed

    private void btEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarProductoActionPerformed
        eliminarProductos(Tabla.getSelectedRow());
        
        inicializaTabla(Tabla);
    }//GEN-LAST:event_btEliminarProductoActionPerformed

    private void btAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarProductoActionPerformed
        
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        int idProducto = 0;
        String nombreProducto="";
        double precioProducto = 0.0;
        int cantidadProducto = 0;
        
        try {
            Statement instruccion3 = cnx.createStatement();
            ResultSet rs1 = instruccion3.executeQuery("select * from inventario where Nombre = '"
                + this.comboProductos.getSelectedItem()+ "'");
            while(rs1.next()){
                idProducto = rs1.getInt("idProducto");
                nombreProducto = rs1.getString("Nombre");
                cantidadProducto = rs1.getInt("CantidadKg");
                precioProducto = rs1.getDouble("PrecioKg");
                
            }
            
            agregarProducto(idProducto, nombreProducto, precioProducto);
            inicializaTabla(Tabla);
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btAgregarProductoActionPerformed

    private void btVerTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerTotalActionPerformed
        lbTotalDato.setText(Double.toString(this.sumaTotal));
    }//GEN-LAST:event_btVerTotalActionPerformed

    private void btFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarActionPerformed
        // TODO add your handling code here:
        /*
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        Random rnd = new Random();
        
        
        try{
        Statement instruccion3 = cnx.createStatement();
            ResultSet rs1 = instruccion3.executeQuery("select * from clientes where Nombre = '"
                + this.comboClientes.getSelectedItem()+ "'");
             
        
        while(rs1.next()){
        int IDVenta =  rnd.nextInt();
                //Integer.parseInt(txtIdCliente.getText());
        String FechaDeVenta = lbFechaDato.getText();
        String NombreCliente = rs1.getString("Nombre");
        String DireccionCliente = "";
                //rs1.getString("Direccion");
        double PrecioVenta = this.sumaTotal;
        String DetallesVenta = "";
        
         Ventas nuevaVenta = new Ventas(IDVenta, FechaDeVenta, NombreCliente, DireccionCliente, PrecioVenta, DetallesVenta);
         String sql = " INSERT INTO ventas (IDVenta, FechaDeVenta, NombreCliente, DireccionCliente, PrecioVenta, DetallesVenta) VALUES ( "+nuevaVenta.getIdVenta()+" , '"+nuevaVenta.getFechaDeVenta()+"' , "+nuevaVenta.getNombreCliente()+" , "+nuevaVenta.getDireccionCliente()+" , "+nuevaVenta.getPrecioVenta()+" , "+nuevaVenta.getDetallesVenta()+" ) ";
           // para que se pueda comunicar la instrucción a la bd
            Statement instruccion = cnx.createStatement(); //
            // ejecutando la instrucción y actualizando la bd
            instruccion.executeUpdate(sql);   
        }
        
    }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
    }
        */
        

    }//GEN-LAST:event_btFinalizarActionPerformed

    private void comboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClientesActionPerformed
        // TODO add your handling code here:
        
        ConectaBD cnc = new ConectaBD();
        Connection cnx = cnc.conectar();
        
        
        try {
            Statement instruccion2 = cnx.createStatement();
            ResultSet rs1 = instruccion2.executeQuery("select * from clientes where Nombre = '"
                    + this.comboClientes.getSelectedItem()+ "'");
            rs1.next();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_comboClientesActionPerformed
    
    
    
    
    public void agregarProducto(int idProducto, 
                                String nombreProducto,
                                //int cantidadProducto, 
                                double precioProducto
                                ){
        
            ArregloProductos.add(new Producto(nombreProducto, precioProducto));
    }
    
    
    
    
 
    public void eliminarProductos(int indice){
        ArregloProductos.remove(indice);        
    }
    
    
    
    
    //Método para listar los datos en la tabla
    public void inicializaTabla(JTable tabla){
  
        Vector <String> titulos = new Vector<String>();
        Vector <Vector <Object>> data = new Vector <Vector <Object>>();
        sumaTotal = 0.0;
        
        titulos.add("IDProducto");
        titulos.add("Nombre");
        titulos.add("Cantidad");
        titulos.add("Precio");
            
            
        for(int i=0; i<ArregloProductos.size(); i++){
            Vector<Object> row = new Vector<Object>();
            
            row.add(((Producto) ArregloProductos.get(i)).getId() );
            row.add(((Producto) ArregloProductos.get(i)).getNombre() );
            //row.add(((Producto) ArregloProductos.get(i)).getCantidadProducto() );
            row.add(((Producto) ArregloProductos.get(i)).getPrecio() );
            
            sumaTotal = sumaTotal + ((Producto) ArregloProductos.get(i)).getPrecio();
            data.add(row);            
        }
        
        DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(data, titulos);
        this.establecerModeloJTable(modelo, tabla); 

    }
    
    
    
    
    
    private void establecerModeloJTable(DefaultTableModel modelo, JTable tabla){
        tabla.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btAgregarProducto;
    private javax.swing.JButton btEliminarProducto;
    private javax.swing.JButton btFinalizar;
    private javax.swing.JButton btRegresarMenu;
    private javax.swing.JButton btVerTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboClientes;
    private javax.swing.JComboBox<String> comboProductos;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbFechaDato;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JLabel lbRelojDato;
    private javax.swing.JLabel lbTituloVentas;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalDato;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
