/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.Operaciones.Pedidor;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import Vista.Tablas.ModeloTablaGrupoProd;
import Negocio.Entidades.GrupoProds;
import Negocio.Entidades.Producto;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author DEMON
 */
public class RegistradorPedidos extends javax.swing.JFrame {
    Pedidor pedidor = new Pedidor();
    List<String> nombresProdsDisp = pedidor.getNombresTodosProd();
    List<GrupoProds> gruposProdActuales = new ArrayList<>();
    double costoTotal;
    /**
     * Creates new form registradorPedidos
     */
    public RegistradorPedidos() {
        initComponents();
        rellenarListaGrupoProd(gruposProdActuales);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelComprador = new javax.swing.JPanel();
        LabelComprador = new javax.swing.JLabel();
        TextoComprador = new javax.swing.JTextField();
        LabelDireccion = new javax.swing.JLabel();
        TextoDireccion = new javax.swing.JTextField();
        LabelTelefono = new javax.swing.JLabel();
        TextoTelefono = new javax.swing.JTextField();
        LabelCampos = new javax.swing.JLabel();
        LabelFecha = new javax.swing.JLabel();
        comboFecha = new datechooser.beans.DateChooserCombo();
        LabelHora = new javax.swing.JLabel();
        TextoHora = new javax.swing.JTextField();
        PanelGruposProds = new javax.swing.JPanel();
        ScrollGruposProd = new javax.swing.JScrollPane();
        TablaGruposProd = new javax.swing.JTable();
        ComboProds = new javax.swing.JComboBox<String>();
        LabelProducto = new javax.swing.JLabel();
        LabelCantidad = new javax.swing.JLabel();
        TextoCantidad = new javax.swing.JTextField();
        BotonAgregar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        TextoTotal = new javax.swing.JTextField();
        LabelTotal = new javax.swing.JLabel();
        BotonRegistrar = new javax.swing.JToggleButton();
        BotonCancelar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar un Pedido");

        LabelComprador.setText("Comprador *");

        LabelDireccion.setText("Dirección *");

        LabelTelefono.setText("Telefono");

        LabelCampos.setText("* Campos obligatorios");

        LabelFecha.setText("Fecha *");

        LabelHora.setText("Hora *");

        javax.swing.GroupLayout PanelCompradorLayout = new javax.swing.GroupLayout(PanelComprador);
        PanelComprador.setLayout(PanelCompradorLayout);
        PanelCompradorLayout.setHorizontalGroup(
            PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCompradorLayout.createSequentialGroup()
                        .addComponent(LabelComprador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoComprador))
                    .addGroup(PanelCompradorLayout.createSequentialGroup()
                        .addComponent(LabelDireccion)
                        .addGap(14, 14, 14)
                        .addComponent(TextoDireccion))
                    .addGroup(PanelCompradorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelCampos)
                        .addContainerGap())
                    .addGroup(PanelCompradorLayout.createSequentialGroup()
                        .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFecha)
                            .addComponent(LabelTelefono))
                        .addGap(24, 24, 24)
                        .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCompradorLayout.createSequentialGroup()
                                .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TextoTelefono)))))
        );
        PanelCompradorLayout.setVerticalGroup(
            PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCompradorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelComprador)
                    .addComponent(TextoComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDireccion)
                    .addComponent(TextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTelefono)
                    .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PanelCompradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFecha)
                    .addComponent(comboFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(LabelCampos)
                .addContainerGap())
        );

        PanelGruposProds.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos Seleccionados"));

        TablaGruposProd.setModel(new ModeloTablaGrupoProd());
        ScrollGruposProd.setViewportView(TablaGruposProd);

        ComboProds.setModel(new DefaultComboBoxModel(nombresProdsDisp.toArray()));

        LabelProducto.setText("Producto:");

        LabelCantidad.setText("Cantidad:");

        TextoCantidad.setToolTipText("Ingrese la cantidad de productos");

        BotonAgregar.setText("Agregar");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        TextoTotal.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        TextoTotal.setEnabled(false);
        TextoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTotalActionPerformed(evt);
            }
        });

        LabelTotal.setText("TOTAL:");

        javax.swing.GroupLayout PanelGruposProdsLayout = new javax.swing.GroupLayout(PanelGruposProds);
        PanelGruposProds.setLayout(PanelGruposProdsLayout);
        PanelGruposProdsLayout.setHorizontalGroup(
            PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGruposProdsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollGruposProd)
                    .addGroup(PanelGruposProdsLayout.createSequentialGroup()
                        .addComponent(LabelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboProds, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(LabelTotal)
                        .addGap(18, 18, 18)
                        .addComponent(TextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        PanelGruposProdsLayout.setVerticalGroup(
            PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGruposProdsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollGruposProd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboProds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProducto)
                    .addComponent(LabelCantidad)
                    .addComponent(TextoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(PanelGruposProdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEliminar)
                    .addComponent(TextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTotal)))
        );

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        BotonCancelar.setText("Cancelar");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelComprador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelGruposProds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGruposProds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistrar)
                    .addComponent(BotonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTotalActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        agregarNuevoGrupoProd(ComboProds.getSelectedItem().toString(),TextoCantidad.getText());
        actualizarListaGrupoProd();
        actualizarCostoTotal();
    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        EnviarInputs();
        FinalizarRegistroPedido();
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        gruposProdActuales.remove(getGrupoProdSeleccionado());
        actualizarListaGrupoProd();
        actualizarCostoTotal();
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void agregarNuevoGrupoProd(String NombreProd, String InputCantidad) {
        gruposProdActuales.add(crearNuevoGrupoProd(NombreProd, InputCantidad));
    }
    
    private GrupoProds crearNuevoGrupoProd(String NombreProd, String InputCantidad){
        Producto prod = pedidor.getProdPorNombre(NombreProd);
        int cantidad = Integer.parseInt(InputCantidad);
        GrupoProds nuevoGrupoProd = new GrupoProds(prod, cantidad);
        return nuevoGrupoProd;
    }

    private void actualizarListaGrupoProd() {
        vaciarListaGrupoProd();
        rellenarListaGrupoProd(gruposProdActuales);
    }

    private void vaciarListaGrupoProd() {
        ModeloTablaGrupoProd mtgp = getModeloTablaGrupoProd();
        int rowCount = mtgp.getRowCount();
        for (int i = rowCount - 1; 0 <= i; i--) {
            mtgp.removerFila(i);
        }    
    }

    private void rellenarListaGrupoProd(List<GrupoProds> gruposProdActuales) {
        getModeloTablaGrupoProd().agregarVariasFilas(gruposProdActuales);
    }

    private ModeloTablaGrupoProd getModeloTablaGrupoProd() {
        return (ModeloTablaGrupoProd) TablaGruposProd.getModel();
    }
    
    private String getHora() {
        return TextoHora.getText();
    }
    
    private String getDireccion(){
        return TextoDireccion.getText();
    }
    
    private String getTelefono(){
        return TextoTelefono.getText();
    }
    
    private String getComprador(){
        return TextoComprador.getText();
    }
    
    private Date getFechaEntrega() {
        Calendar selectedDateChooserCalendar = comboFecha.getSelectedDate();
        
        return selectedDateChooserCalendar.getTime();
    }
    
    private void EnviarInputs() {
        pedidor.setDireccion(getDireccion());
        pedidor.setNombreComprador(getComprador());
        pedidor.setGruposProdsSeleccionados(getGruposProdActuales());
        pedidor.setTelefono(getTelefono());
        pedidor.setHora(getHora());
        pedidor.setCosto(getCostoTotal());
        pedidor.setFechaEntrega(getFechaEntrega());
        pedidor.guardarPedido();
        
    }

    public List<GrupoProds> getGruposProdActuales() {
        return gruposProdActuales;
    }

    public void setGruposProdActuales(List<GrupoProds> gruposProdActuales) {
        this.gruposProdActuales = gruposProdActuales;
    }

    private boolean seSeleccionoFilaVacia() {
        int INDICE_NINGUNA_FILA = -1;
        
        return (getFilaSeleccionada() == INDICE_NINGUNA_FILA);    }

    private int getFilaSeleccionada() {
        return TablaGruposProd.getSelectedRow();
    }

    private void actualizarCostoTotal() {
        costoTotal = 0;
        for(GrupoProds actual : gruposProdActuales){
            costoTotal += actual.getCostoGrupoProd();
        }
        TextoTotal.setText(String.valueOf(costoTotal));
    }

    public double getCostoTotal() {
        return costoTotal;
    }

    private GrupoProds getGrupoProdSeleccionado() {
        if(!seSeleccionoFilaVacia()){
            int filaSeleccionada = getFilaSeleccionada();
            GrupoProds grupoSeleccionado = getModeloTablaGrupoProd().getFila(filaSeleccionada);
            return grupoSeleccionado;
        }else{
            System.err.println("No se selecciono una fila");
            return null;
        }    
    }

    private void FinalizarRegistroPedido() {
        this.setVisible(false);
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JToggleButton BotonCancelar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JToggleButton BotonRegistrar;
    private javax.swing.JComboBox<String> ComboProds;
    private javax.swing.JLabel LabelCampos;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelComprador;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelFecha;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelProducto;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JPanel PanelComprador;
    private javax.swing.JPanel PanelGruposProds;
    private javax.swing.JScrollPane ScrollGruposProd;
    private javax.swing.JTable TablaGruposProd;
    private javax.swing.JTextField TextoCantidad;
    private javax.swing.JTextField TextoComprador;
    private javax.swing.JTextField TextoDireccion;
    private javax.swing.JTextField TextoHora;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JTextField TextoTotal;
    private datechooser.beans.DateChooserCombo comboFecha;
    // End of variables declaration//GEN-END:variables

}
